CATEGORY_KEYWORDS = {
    "Food": [
        "pizza",
        "burger",
        "restaurant",
        "food",
        "cafe",
        "coffee",
        "dominos",
        "kfc",
        "mcdonald",
        "swiggy",
        "zomato",
    ],
    "Travel": [
        "uber",
        "ola",
        "bus",
        "train",
        "flight",
        "taxi",
        "metro",
        "petrol",
        "diesel",
        "fuel",
    ],
    "Shopping": [
        "amazon",
        "flipkart",
        "mall",
        "shopping",
        "clothes",
        "shirt",
        "shoes",
    ],
    "Entertainment": [
        "movie",
        "netflix",
        "spotify",
        "prime",
        "cinema",
        "game",
    ],
    "Bills": [
        "electricity",
        "water",
        "internet",
        "wifi",
        "recharge",
        "rent",
        "gas",
    ],
    "Health": [
        "hospital",
        "doctor",
        "medicine",
        "medical",
        "pharmacy",
        "gym",
    ],
    "Education": [
        "college",
        "course",
        "book",
        "exam",
        "fees",
        "tuition",
    ],
}