import {useEffect,useMemo,useState} from "react";
import {Search,Plus,Trash2,Edit3,ReceiptText,X,Save} from "lucide-react";
import {Link,useSearchParams} from "react-router-dom";
import {deleteExpense,getExpenses,updateExpense} from "../services/api";
import {CATEGORIES,money,shortDate} from "../utils/format";
import "./FinancePages.css";
export default function Expenses(){const [params]=useSearchParams();const [expenses,setExpenses]=useState([]);const [search,setSearch]=useState("");const [category,setCategory]=useState(params.get("category")||"");const [editing,setEditing]=useState(null);const [error,setError]=useState("");
async function load(){try{setExpenses(await getExpenses({search,category,limit:100})||[]);setError("")}catch(e){setError(e.message)}}useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[search,category]);
async function remove(id){if(!window.confirm("Delete this expense?"))return;try{await deleteExpense(id);setExpenses(x=>x.filter(e=>e.id!==id))}catch(e){setError(e.message)}}
async function save(e){e.preventDefault();try{const updated=await updateExpense(editing.id,{title:editing.title,amount:Number(editing.amount),description:editing.description||null,expense_date:editing.expense_date});setExpenses(x=>x.map(i=>i.id===updated.id?updated:i));setEditing(null)}catch(e){setError(e.message)}}
return <div className="finance-page"><div className="page-heading"><div><p className="eyebrow">ACTIVITY</p><h1>Expenses</h1><p>Search, review and manage every expense.</p></div><Link to="/expenses/add" className="primary-btn"><Plus size={17}/> Add Expense</Link></div>{error&&<div className="error-banner">{error}</div>}
<div className="toolbar"><div className="search-box"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search expenses..."/></div><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></div>
<div className="table-card"><div className="table-head"><span>Expense</span><span>Category</span><span>Date</span><span>Amount</span><span>Actions</span></div>{expenses.length?expenses.map(e=><div className="table-row" key={e.id}><div className="expense-cell"><div className="expense-avatar">{e.category?.slice(0,1)||"E"}</div><div><strong>{e.title}</strong><small>{e.description||"No description"}</small></div></div><span className="pill">{e.category}</span><span>{shortDate(e.expense_date)}</span><strong>{money(e.amount)}</strong><div className="row-actions"><button onClick={()=>setEditing({...e})}><Edit3 size={16}/></button><button className="danger" onClick={()=>remove(e.id)}><Trash2 size={16}/></button></div></div>):<div className="empty large"><ReceiptText size={30}/><strong>No expenses found</strong><span>Try another search or add a new expense.</span></div>}</div>
{editing&&<div className="modal-backdrop"><form className="modal" onSubmit={save}><div className="modal-title"><h2>Edit Expense</h2><button type="button" onClick={()=>setEditing(null)}><X/></button></div><label>Title<input value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})} required/></label><div className="form-grid"><label>Amount<input type="number" min="0.01" step="0.01" value={editing.amount} onChange={e=>setEditing({...editing,amount:e.target.value})} required/></label><label>Date<input type="date" value={editing.expense_date} onChange={e=>setEditing({...editing,expense_date:e.target.value})} required/></label></div><label>Description<textarea rows="3" value={editing.description||""} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><button className="primary-btn"><Save size={16}/> Save Changes</button></form></div>}</div>}
